name: compile wsl2 kernel
on: 
  workflow_dispatch:
env:
  stable_version: 6.5.5
jobs:
  build:
    runs-on: ubuntu-latest
    container: zhoneym/unofficial-archrootfs-workstations:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build commands
        run: |
          wget https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/archive/refs/tags/linux-wsl-stable-${{ env.stable_version }}.tar.gz
          tar -xzf linux-wsl-stable-${{ env.stable_version }}.tar.gz
          cd WSL2-Linux-Kernel-Rolling-linux-wsl-stable-${{ env.stable_version }}
          sed -i 's/-WSL2-STABLE/-x86_64-wsl2/g' arch/x86/configs/config-wsl-x86
          make KCONFIG_CONFIG=arch/x86/configs/config-wsl-x86 -j $(nproc) CFLAGS="-march=x86-64-v3 -mtune=native -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -mcx16 -mpopcnt -msse4.1 -msse4.2 -mssse3 -mavx -mavx2 -mbmi -mbmi2 -mf16c -mfma -mmovbe -mxsave" CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS" LTOFLAGS="-flto=thin -falign-functions=32" RUSTFLAGS="-Copt-level=3 -Ctarget-cpu=x86-64-v3" GOAMD64="v3"
          cp arch/x86/boot/bzImage ../stable-bzImage-${{ env.stable_version }}-x86_64-wsl2
          mkdir -p ../${{ env.stable_version }}-x86_64-wsl2_install
          make modules_install INSTALL_MOD_PATH=../${{ env.stable_version }}-x86_64-wsl2_install CFLAGS="-march=x86-64-v3 -mtune=native -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -mcx16 -mpopcnt -msse4.1 -msse4.2 -mssse3 -mavx -mavx2 -mbmi -mbmi2 -mf16c -mfma -mmovbe -mxsave" CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS" LTOFLAGS="-flto=thin -falign-functions=32" RUSTFLAGS="-Copt-level=3 -Ctarget-cpu=x86-64-v3" GOAMD64="v3"
          rm -rf ../${{ env.stable_version }}-x86_64-wsl2_install/lib/modules/${{ env.stable_version }}-x86_64-wsl2/build
          mkdir -p ../${{ env.stable_version }}-x86_64-wsl2_install/lib/modules/${{ env.stable_version }}-x86_64-wsl2/build
          local builddir=../${{ env.stable_version }}-x86_64-wsl2_install/lib/modules/${{ env.stable_version }}-x86_64-wsl2/build
          install -Dt "$builddir" -m644 Makefile Module.symvers System.map vmlinux
          install -Dt "$builddir/kernel" -m644 kernel/Makefile
          install -Dt "$builddir/arch/x86" -m644 arch/x86/Makefile
          cp -t "$builddir" -a scripts
          install -Dt "$builddir/tools/objtool" tools/objtool/objtool
          install -Dt "$builddir/tools/bpf/resolve_btfids" tools/bpf/resolve_btfids/resolve_btfids
          cp -t "$builddir" -a include
          cp -t "$builddir/arch/x86" -a arch/x86/include
          install -Dt "$builddir/arch/x86/kernel" -m644 arch/x86/kernel/asm-offsets.s
          install -Dt "$builddir/drivers/md" -m644 drivers/md/*.h
          install -Dt "$builddir/net/mac80211" -m644 net/mac80211/*.h
          install -Dt "$builddir/drivers/media/i2c" -m644 drivers/media/i2c/msp3400-driver.h
          install -Dt "$builddir/drivers/media/usb/dvb-usb" -m644 drivers/media/usb/dvb-usb/*.h
          install -Dt "$builddir/drivers/media/dvb-frontends" -m644 drivers/media/dvb-frontends/*.h
          install -Dt "$builddir/drivers/media/tuners" -m644 drivers/media/tuners/*.h
          install -Dt "$builddir/drivers/iio/common/hid-sensors" -m644 drivers/iio/common/hid-sensors/*.h
          find . -name 'Kconfig*' -exec install -Dm644 {} "$builddir/{}" \;
          local arch
          for arch in "$builddir"/arch/*/; do
            [[ $arch = */x86/ ]] && continue
            echo "Removing $(basename "$arch")"
            rm -r "$arch"
          done
          find -L "$builddir" -type l -printf 'Removing %P\n' -delete
          find "$builddir" -type f -name '*.o' -printf 'Removing %P\n' -delete
          local file
          while read -rd '' file; do
            case "$(file -Sib "$file")" in
            application/x-sharedlib\;*)
                strip -v $STRIP_SHARED "$file" ;;
            application/x-archive\;*)
              strip -v $STRIP_STATIC "$file" ;;
            application/x-executable\;*)
              strip -v $STRIP_BINARIES "$file" ;;
            application/x-pie-executable\;*)
              strip -v $STRIP_SHARED "$file" ;;
            esac
          done < <(find "$builddir" -type f -perm -u+x ! -name vmlinux -print0)
          strip -v $STRIP_STATIC "$builddir/vmlinux"
          mkdir -p ../${{ env.stable_version }}-x86_64-wsl2_install/src
          ln -sr "$builddir" "../${{ env.stable_version }}-x86_64-wsl2_install/src/${{ env.stable_version }}-x86_64-wsl2"
          tar -c --zstd -f ${{ env.stable_version }}-x86_64-wsl2_install.tar.zst ${{ env.stable_version }}-x86_64-wsl2_install
          sha256sum ${{ env.stable_version }}-x86_64-wsl2_install.tar.zst > ${{ env.stable_version }}-x86_64-wsl2_install.tar.zst.sha256
          cp ${{ env.stable_version }}-x86_64-wsl2_install.tar.zst ../
          cp ${{ env.stable_version }}-x86_64-wsl2_install.tar.zst.sha256 ../
          cd ..
          sha256sum stable-bzImage-${{ env.stable_version }}-x86_64-wsl2 > stable-bzImage-${{ env.stable_version }}-x86_64-wsl2.sha256
          tar -cJf WSL2-Linux-Kernel-Rolling-linux-wsl-stable-${{ env.stable_version }}.tar.zst WSL2-Linux-Kernel-Rolling-linux-wsl-stable-${{ env.stable_version }}/
  


      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            stable-bzImage-${{ env.stable_version }}-x86_64-wsl2
            ${{ env.stable_version }}-x86_64-wsl2_install.tar.zst
            stable-bzImage-${{ env.stable_version }}-x86_64-wsl2.sha256
            ${{ env.stable_version }}-x86_64-wsl2_install.tar.zst.sha256
            WSL2-Linux-Kernel-Rolling-linux-wsl-stable-${{ env.stable_version }}.tar.zst
            

  release:
    runs-on: ubuntu-latest
    needs: build
    env:
      TAG_VERSION: "stable-2023-10-03"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: release_images/
      - name: Release Kernel
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.TAG_VERSION }}
          tag_name: ${{ env.TAG_VERSION }}
          body: |
            **How to apply this kernel?**
            Before you try to apply this kernel, You **MUST** shutdown your WSL. (wsl --shutdown)
            Check this [document](https://learn.microsoft.com/en-us/windows/wsl/wsl-config).

            **This kernel built on Arch-Linux, Optimized for x86_64-v3 architectures. **

          files: |
            release_images/*
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
